### ISSUE TITLE
 路由变化不会trackpageview?

### ISSUE THREAD

**Issue by NoraGithub** [raychenfj/vue-uweb#3]
如题。
这个为什么不自动处理了？建议哦。

**Comment by raychenfj** [comment]
vue-router 的路由的变化实际上只是改变了 url 中的 hash 部分，目前大部分的埋点统计工具都不会把这当成加载新页面，只有改变了整个url或其中的查询参数才会认为是加载页面。

对应的解决办法是在路由或页面的生命周期中自己调用 trackPageview 自己进行统计。

**Comment by NoraGithub** [comment]
建议markdown 写一下。
SPA而言。URL变化也许就理解成新的page了。我当时也以为这样子的。以为可以快速部署。后来因为不满足需求，读了源码才发现误会了。
