### ISSUE TITLE
loading uweb statistics script failed, please check src and siteId

### ISSUE THREAD

**Issue by Baymaxxx** [raychenfj/vue-uweb#4]
线上代码没有改动过，友盟也没有碰过，然后突然的报错。

**Comment by raychenfj** [comment]
@Baymaxxx 
由于友盟的脚本地址域名有变动，所以请尝试 https://s95.cnzz.com/z_stat.php?id=${siteId}&web_id=${siteId} 是否能正常访问，如果无法访问可以设置 src 属性指定 uweb 脚本地址

**Comment by maplehsu** [comment]
siteId 是 只申请的key 还是什么？
