### ISSUE TITLE
this._cached push？

### ISSUE THREAD

**Issue by NoraGithub** [raychenfj/vue-uweb#5]
https://github.com/raychenfj/vue-uweb/blob/ba0d082d3e5edab46e76c9af601474da0db6ca6d/src/index.js#L48

Why don't we just push here?

Take the below as an example:

when argument = ['_trackPageView','/']
this._cached = []
afiter the function, this._cached would become ['_trackPageView','/'].
but what we really need is [['_trackPageView','/']].

**Comment by raychenfj** [comment]
@NoraGithub 

Thanks for coming.

Here is a little explanation:

the ```_cache``` is used to store API arguments if you call them before initiation is complete.
When initiation is done, will use the arguments store in ```_cache``` to call the API again automatically.

And actually, the ```_cache``` is indeed a nested array. ```arguments``` is an array-like structure, so when you push it into an array, then it becomes a nested array.

You can try the sample script below in node, and you will see how it works.

```javascript
const cache = []

function push () {
  cache.push(arguments)
}

push(['_trackPageView','/'])

console.log(JSON.stringify(cache))
```

**Comment by NoraGithub** [comment]
Well, I don't think your code was doing what you describe above.
In my opinion, your `push` would like `concat`.
