### ISSUE TITLE
ssr项目中不支持此插件，作者能否更新一下？

### ISSUE THREAD

**Issue by iNuoers** [raychenfj/vue-uweb#6]

**Comment by raychenfj** [comment]
support ssr in this commit 😃

https://github.com/raychenfj/vue-uweb/commit/1132d6f036fb6dfe804abfcdd9c29871daf110cc#diff-9f06c51911da08ebd6400ff77d629c1e

**Comment by iNuoers** [comment]
ok , Thank you very much !
